// ⚠️ Ne pas modifier ce fichier — Do not edit this file
import type { Plugin } from 'vite'
import type { ResumeConfig } from './src/data/types'
import fs from 'fs'
import path from 'path'

/**
 * Vite plugin that validates the resume config at build time.
 *
 * Prints clear, human-readable warnings in the build logs (visible in GitHub Actions).
 * Does NOT block the build — warnings only.
 */

const IMAGE_EXTENSIONS = ['.jpg', '.jpeg', '.png', '.webp']

export function resumeValidatePlugin(): Plugin {
  return {
    name: 'resume-validate',

    async buildStart() {
      let config: ResumeConfig

      const url = import.meta.env.VITE_RESSOURCES_URL;
      if (!url) {
        console.warn('[resume-seo] VITE_RESSOURCES_URL is not defined, skipping SEO injection.');
        return;
      }
      // Dynamically import the resume config (works because Vite resolves TS)
      try {
        // Fetch the JSON config dynamically
        const res = await fetch(`${url}cv-config.json`);
        if (!res.ok) throw new Error(`Failed to fetch cv-config.json: ${res.statusText}`);
        
        // Assert the type
        config = (await res.json()) as ResumeConfig
      } catch {
        console.warn('\n⚠️  [resume-validate] Impossible de charger resume-config.ts — vérification ignorée.\n')
        return
      }

      const publicDir = path.resolve(process.cwd(), 'public')
      const warnings: string[] = []

      // --- Check for example data (Jane Doe) ---
      if (
        config.personal.name.toLowerCase().includes('jane') &&
        config.personal.name.toLowerCase().includes('doe')
      ) {
        warnings.push(
          '⚠️  Vous utilisez encore les données d\'exemple (Jane Doe).\n' +
          '   Remplacez-les par vos informations dans src/data/resume-config.ts',
        )
      }

      // --- Check photo ---
      const imagesDir = path.join(publicDir, 'images')
      if (config.personal.photo) {
        // Check if explicitly referenced photo exists
        const photoPath = path.join(publicDir, config.personal.photo)
        if (!fs.existsSync(photoPath)) {
          warnings.push(
            `⚠️  L'image "${config.personal.photo}" n'existe pas dans public/.\n` +
            '   Vérifiez le nom du fichier ou déposez votre photo/image de profil dans public/images/',
          )
        }
      } else {
        // Check if any image exists for auto-detection
        const hasImage = fs.existsSync(imagesDir) &&
          fs.readdirSync(imagesDir).some((f) => IMAGE_EXTENSIONS.includes(path.extname(f).toLowerCase()))
        if (!hasImage) {
          warnings.push(
            '⚠️  Aucune image trouvée dans public/images/.\n' +
            '   Ajoutez votre photo ou image de profil (JPG ou PNG, format carré recommandé).',
          )
        }
      }

      // --- Check PDF paths if explicitly configured ---
      if (config.pdf) {
        const pdfPaths: string[] = []
        if (typeof config.pdf.path === 'string') {
          pdfPaths.push(config.pdf.path)
        } else {
          pdfPaths.push(...Object.values(config.pdf.path))
        }
        for (const pdfPath of pdfPaths) {
          const fullPath = path.join(publicDir, pdfPath)
          if (!fs.existsSync(fullPath)) {
            warnings.push(
              `❌ Le fichier PDF "${pdfPath}" n'existe pas dans public/.\n` +
              '   Vérifiez le chemin ou déposez vos PDFs dans public/cv/fr/ et public/cv/en/',
            )
          }
        }
      }

      // --- Print warnings ---
      if (warnings.length > 0) {
        console.warn('\n' + '='.repeat(60))
        console.warn('📋 Vérification du CV — Resume validation')
        console.warn('='.repeat(60))
        for (const warning of warnings) {
          console.warn('\n' + warning)
        }
        console.warn('\n' + '='.repeat(60) + '\n')
      }
    },
  }
}
